import sys
from pathlib import Path

import pytest

# Ensure the package src directory is on PYTHONPATH for imports
repo_root = Path(__file__).resolve().parents[1]
src_path = repo_root / "src"
sys.path.insert(0, str(src_path))

# Import the CLI entry point from the package
from dbf_bridge.cli import main, _resolve_formats, _resolve_memo_policy, ALL_FORMATS

@pytest.fixture(scope="module")
def sample_input_dir() -> Path:
    """Path to the generated synthetic DBF fixtures used by the test suite."""
    return Path(__file__).parent / "fixtures" / "input"


def test_resolve_formats_valid():
    # Normal comma‑separated list
    assert _resolve_formats("csv,json") == ["csv", "json"]
    # Duplicate entries are deduped while preserving order
    assert _resolve_formats("json,csv, json") == ["json", "csv"]
    # Empty string returns the full set of supported formats
    assert set(_resolve_formats("")) == set(ALL_FORMATS)


def test_resolve_formats_invalid():
    with pytest.raises(ValueError):
        _resolve_formats("unsupported, csv")


def test_resolve_memo_policy():
    # Explicit argument overrides default policy
    assert _resolve_memo_policy("csv", "inline") == "inline"
    # Default memo policy per format is applied when argument is None
    for fmt, expected in {
        "csv": "skip",
        "json": "inline",
        "jsonl": "inline",
        "xlsx": "inline",
    }.items():
        assert _resolve_memo_policy(fmt, None) == expected


def test_export_example(sample_input_dir: Path):
    """Integration test that runs the CLI against the synthetic fixtures.

    The test verifies:
    * The CLI returns a zero exit code.
    * Output files for each table and format are created.
    * Migration report files are generated.
    """
    # Build argument list – use explicit formats to keep the check deterministic
    args = [
        "--source",
        str(sample_input_dir),
        "--output",
        str(tmp_path),
        "--formats",
        "csv,json,jsonl",
    ]

    exit_code = main(args)
    assert exit_code == 0, f"CLI exited with non‑zero code {exit_code}"

    # Expected output files (relative to the output directory)
    expected_paths = [
        tmp_path / "klienci.csv",
        tmp_path / "klienci.json",
        tmp_path / "klienci.jsonl",
        tmp_path / "zamowienia" / "zamowienia.csv",
        tmp_path / "zamowienia" / "zamowienia.json",
        tmp_path / "zamowienia" / "zamowienia.jsonl",
        tmp_path / "archiwum" / "stare_dane.csv",
        tmp_path / "archiwum" / "stare_dane.json",
        tmp_path / "archiwum" / "stare_dane.jsonl",
        # Reports generated by the exporter
        tmp_path / "migration_report.jsonl",
        tmp_path / "migration_report.csv",
    ]

    missing = [p for p in expected_paths if not p.is_file()]
    assert not missing, f"Missing output files: {missing}"
