import json
from pathlib import Path

import pytest

from dbf_bridge.cli import ALL_FORMATS, _resolve_formats, _resolve_memo_policy, main


@pytest.fixture(scope="module")
def sample_input_dir() -> Path:
    """Path to the generated synthetic DBF fixtures used by the test suite."""
    return Path(__file__).parent / "fixtures" / "input"


def test_resolve_formats_valid():
    # Normal comma‑separated list
    assert _resolve_formats("csv,json") == ["csv", "json"]
    # Duplicate entries are deduped while preserving order
    assert _resolve_formats("json,csv, json") == ["json", "csv"]
    # Empty string returns the full set of supported formats
    assert set(_resolve_formats("")) == set(ALL_FORMATS)


def test_resolve_formats_invalid():
    with pytest.raises(ValueError):
        _resolve_formats("unsupported, csv")


def test_resolve_memo_policy():
    # Explicit argument overrides default policy
    assert _resolve_memo_policy("csv", "inline") == "inline"
    # Default memo policy per format is applied when argument is None
    for fmt, expected in {
        "csv": "skip",
        "json": "inline",
        "jsonl": "inline",
        "xlsx": "inline",
    }.items():
        assert _resolve_memo_policy(fmt, None) == expected


def test_export_example(sample_input_dir: Path):
    """Integration test that runs the CLI against the synthetic fixtures.

    Uses a temporary directory inside the repository to avoid permission issues
    with pytest's default tmp_path fixture.
    """
    # Prepare a clean output directory within the repo
    output_dir = Path(__file__).parent / "tmp_output"
    if output_dir.exists():
        for p in sorted(output_dir.rglob("*"), key=lambda x: -len(str(x))):
            if p.is_file():
                p.unlink()
            else:
                p.rmdir()
    output_dir.mkdir(parents=True, exist_ok=True)

    args = [
        "--source",
        str(sample_input_dir),
        "--output",
        str(output_dir),
        "--formats",
        "csv,json,jsonl,xlsx",
    ]

    exit_code = main(args)
    assert exit_code == 0, f"CLI exited with non‑zero code {exit_code}"

    expected_paths = [
        output_dir / "klienci.jsonl",
        output_dir / "klienci.csv",
        output_dir / "klienci.json",
        output_dir / "klienci.xlsx",
        output_dir / "klienci_schema.json",
        output_dir / "zamowienia" / "zamowienia.jsonl",
        output_dir / "zamowienia" / "zamowienia.csv",
        output_dir / "zamowienia" / "zamowienia.json",
        output_dir / "zamowienia" / "zamowienia.xlsx",
        output_dir / "zamowienia" / "zamowienia_schema.json",
        output_dir / "archiwum" / "stare_dane.jsonl",
        output_dir / "archiwum" / "stare_dane.csv",
        output_dir / "archiwum" / "stare_dane.json",
        output_dir / "archiwum" / "stare_dane.xlsx",
        output_dir / "archiwum" / "stare_dane_schema.json",
        # Reports generated by the exporter
        output_dir / "migration_report.jsonl",
        output_dir / "migration_report.csv",
        output_dir / "conversion_checksums.json",
    ]

    missing = [p for p in expected_paths if not p.is_file()]
    assert not missing, f"Missing output files: {missing}"

    report_lines = [
        json.loads(line)
        for line in (output_dir / "migration_report.jsonl").read_text(encoding="utf-8").splitlines()
    ]
    summary = report_lines[0]
    entries = report_lines[1:]
    assert summary["report_version"] == 4
    assert summary["tables"] == 3
    assert summary["outputs"] == 12
    assert summary["formats"] == ["csv", "json", "jsonl", "xlsx"]
    assert summary["requested_formats"] == ["csv", "json", "jsonl", "xlsx"]
    assert summary["ok"] == 12
    assert summary["skipped"] == 0
    assert summary["failed"] == 0
    assert summary["complete_tables"] == 3
    assert summary["incomplete_tables"] == 0
    assert summary["run"]["exit_code"] == 0
    assert summary["run"]["deleted_policy"] == "skip"
    assert len(entries) == 12
    assert {(entry["table"], entry["format"]) for entry in entries} == {
        (table, fmt)
        for table in [
            "klienci.dbf",
            "zamowienia/zamowienia.dbf",
            "archiwum/stare_dane.dbf",
        ]
        for fmt in ["csv", "json", "jsonl", "xlsx"]
    }
    assert all(entry["sha256"] for entry in entries)
    assert all(entry["schema"] and entry["schema_sha256"] for entry in entries)
