import sys
from pathlib import Path

import pytest

# Ensure the package src directory is on PYTHONPATH for imports
repo_root = Path(__file__).resolve().parents[1]
src_path = repo_root / "src"
sys.path.insert(0, str(src_path))

# Import the CLI entry point from the package
from dbf_bridge.cli import main, _resolve_formats, _resolve_memo_policy, ALL_FORMATS

@pytest.fixture(scope="module")
def sample_input_dir() -> Path:
    """Path to the generated synthetic DBF fixtures used by the test suite."""
    return Path(__file__).parent / "fixtures" / "input"


def test_resolve_formats_valid():
    # Normal comma‑separated list
    assert _resolve_formats("csv,json") == ["csv", "json"]
    # Duplicate entries are deduped while preserving order
    assert _resolve_formats("json,csv, json") == ["json", "csv"]
    # Empty string returns the full set of supported formats
    assert set(_resolve_formats("")) == set(ALL_FORMATS)


def test_resolve_formats_invalid():
    with pytest.raises(ValueError):
        _resolve_formats("unsupported, csv")


def test_resolve_memo_policy():
    # Explicit argument overrides default policy
    assert _resolve_memo_policy("csv", "inline") == "inline"
    # Default memo policy per format is applied when argument is None
    for fmt, expected in {
        "csv": "skip",
        "json": "inline",
        "jsonl": "inline",
        "xlsx": "inline",
    }.items():
        assert _resolve_memo_policy(fmt, None) == expected


def test_export_example(sample_input_dir: Path):
    """Integration test that runs the CLI against the synthetic fixtures.

    Uses a temporary directory inside the repository to avoid permission issues
    with pytest's default tmp_path fixture.
    """
    # Prepare a clean output directory within the repo
    output_dir = Path(__file__).parent / "tmp_output"
    if output_dir.exists():
        for p in sorted(output_dir.rglob("*"), key=lambda x: -len(str(x))):
            if p.is_file():
                p.unlink()
            else:
                p.rmdir()
    output_dir.mkdir(parents=True, exist_ok=True)

    args = [
        "--source",
        str(sample_input_dir),
        "--output",
        str(output_dir),
    ]

    exit_code = main(args)
    assert exit_code == 0, f"CLI exited with non‑zero code {exit_code}"

    expected_paths = [
        output_dir / "klienci.jsonl",
        output_dir / "zamowienia" / "zamowienia.jsonl",
        output_dir / "archiwum" / "stare_dane.jsonl",
        # Reports generated by the exporter
        output_dir / "migration_report.jsonl",
        output_dir / "migration_report.csv",
    ]

    missing = [p for p in expected_paths if not p.is_file()]
    assert not missing, f"Missing output files: {missing}"
