"""PyPI-installation smoke for the optional-dependency split (stdlib only).

Builds (or reuses) a feature wheel and, in a series of FRESH virtual
environments outside the repository, validates the whole install contract:

- **base**        — `pip install <wheel>`: mandatory dependency set contains
  only dbfread (checked via importlib.metadata inventory), `import dbfbridge`
  loads no heavy dependency, and the full Direct Read surface works;
- **migration**   — base install: DBF → JSONL, DBF → JSON, DBF → CSV (stdlib
  and Python fallback engines; no orjson/polars installed);
- **negative**    — without [write]: `reconstruct_dbf` raises
  `OptionalDependencyMissingError` (code OPTIONAL_DEPENDENCY_MISSING) and
  leaves ZERO output artifacts; without [xlsx]: XLSX export fails typed
  before creating anything;
- **[write]**     — JSONL → DBF/FPT reconstruction plus verification;
- **[xlsx]**      — XLSX export; **[write,xlsx]** — XLSX → DBF reconstruction;
- **[fast]**      — orjson/polars importable and results logically identical
  to the fallback engines;
- **[all]**       — the full release wheel smoke (scripts/release_wheel_smoke.py)
  plus reconstruction and XLSX checks.

No PyPI token, no upload, no tag/release interaction: this is a local
install-verification harness.  Fixtures are synthetic and generated by this
script (the outer environment provides `dbf` for that preparation only).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import venv
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
REQUIRED_BASE_ABSENT = ("dbf", "openpyxl", "xlsxwriter", "orjson", "polars")

# ---------------------------------------------------------------------------
# tiny helpers (stdlib only)
# ---------------------------------------------------------------------------


class SmokeFailure(RuntimeError):
    """One smoke step failed; nothing is retried or hidden."""


def _run(command: list[str], *, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(command, capture_output=True, text=True, cwd=cwd)
    if completed.returncode != 0:
        raise SmokeFailure(
            f"command failed ({completed.returncode}): {' '.join(command)}\n"
            f"--- stdout ---\n{completed.stdout[-4000:]}\n--- stderr ---\n{completed.stderr[-4000:]}"
        )
    return completed


def _venv_python(venv_dir: Path) -> Path:
    scripts = venv_dir / "Scripts" if sys.platform.startswith("win") else venv_dir / "bin"
    return scripts / "python.exe" if sys.platform.startswith("win") else scripts / "python"


def make_fresh_venv(parent: Path, name: str) -> Path:
    """Deprecated alias of :func:`build_fresh_venv` (kept for callers)."""
    return build_fresh_venv(parent, name)


def build_fresh_venv(root: Path, name: str) -> Path:
    directory = root / name
    builder = venv.EnvBuilder(with_pip=True, clear=True)
    builder.create(directory)
    return directory


def venv_python(venv_dir: Path) -> Path:
    scripts = venv_dir / "Scripts" if sys.platform.startswith("win") else venv_dir / "bin"
    return scripts / "python.exe" if sys.platform.startswith("win") else scripts / "python"


def pip_install(venv_dir: Path, *spec: str) -> None:
    _run(
        [
            str(venv_python(venv_dir)),
            "-m",
            "pip",
            "install",
            "--force-reinstall",
            "--disable-pip-version-check",
            "--no-input",
            *spec,
        ]
    )


def run_snippet(venv_dir: Path, code: str, *, cwd: Path | None = None) -> str:
    return _run([str(venv_python(venv_dir)), "-c", code], cwd=cwd).stdout


def snippet(venv_dir: Path, code: str, *, cwd: Path | None = None) -> str:
    stdout = _run([str(venv_python(venv_dir)), "-c", code], cwd=cwd).stdout
    for line in stdout.strip().splitlines():
        if line.strip():
            print(f"  [{venv_dir.name}] {line.strip()}")
    return stdout


# ---------------------------------------------------------------------------
# fixture preparation (outer environment; uses the `dbf` writer library)
# ---------------------------------------------------------------------------


def prepare_fixtures(work: Path) -> dict[str, Any]:
    try:
        import dbf  # noqa: F401 - preparation-only dependency
    except ImportError as exc:  # pragma: no cover - environment error
        raise SmokeFailure(
            "fixture preparation needs the `dbf` library in the OUTER environment"
        ) from exc

    flat = work / "fixtures" / "customers.dbf"
    flat.parent.mkdir(parents=True, exist_ok=True)
    table = dbf.Table(
        str(flat),
        field_specs="ID N(6,0); NAME C(30); CITY C(20); AMOUNT N(10,2)",
        dbf_type="vfp",
        codepage=0xC8,
    )
    table.open(mode=dbf.READ_WRITE)
    for index in range(1, 201):
        table.append(
            {
                "ID": index,
                "NAME": f"Klient {index} ąęłóńśćźż",
                "CITY": "Warszawa",
                "AMOUNT": round(index * 1.5, 2),
            }
        )
    table.close()

    memo = work / "fixtures" / "notes.dbf"
    memo_table = dbf.Table(
        str(memo),
        field_specs="ID N(6,0); NOTATKA M",
        dbf_type="vfp",
        codepage=0xC8,
    )
    memo_table.open(mode=dbf.READ_WRITE)
    for index in range(1, 51):
        memo_table.append({"ID": index, "NOTATKA": f"Mazovia memo {index}: żółw, książka, śliwka."})
    memo_table.close()

    # A REAL Mazovia-bytes fixture for the explicit-encoding correctness
    # check.  Built in the OUTER harness with the project's canonical
    # Mazovia table (never hard-coded bytes), so the fresh venv proves the
    # installed wheel decodes genuine Mazovia bytes to the exact text.
    # The expected text is passed to the fresh venv through a UTF-8 JSON
    # sidecar (never embedded in the -c code, which must stay pure ASCII).
    expected_text = "Żółw ąęłóńśćźż Książka"
    mazovia_dbf = work / "fixtures" / "mazovia_real.dbf"
    mazovia_payload = _encode_with_canonical_mazovia(expected_text)
    _write_minimal_mazovia_dbf(mazovia_dbf, "TEKST", mazovia_payload, 1)
    sidecar = work / "fixtures" / "mazovia_expected.json"
    sidecar.write_text(
        json.dumps({"expected": expected_text}, ensure_ascii=False),
        encoding="utf-8",
    )
    return {
        "flat": flat,
        "memo": memo,
        "mazovia_real": mazovia_dbf,
        "mazovia_sidecar": sidecar,
    }


def _encode_with_canonical_mazovia(text: str) -> bytes:
    """Encode *text* with the canonical Mazovia table from core.codecs
    (outer-harness only — the fresh venv never sees this code path)."""
    from dbf_bridge.core.codecs import _MAZOVIA_TABLE, TableCodec

    codec = TableCodec("mazovia", _MAZOVIA_TABLE)
    encoded, _consumed = codec.encode(text)
    return encoded


def _write_minimal_mazovia_dbf(
    path: Path, field_name: str, payload: bytes, record_count: int
) -> None:
    """Hand-write a minimal dBase III DBF storing *payload* (already encoded
    in the target codepage) — stdlib only, no `dbf` writer needed."""
    import struct

    field_length = len(payload)
    header_length = 32 + 32 + 1
    record_length = 1 + field_length
    header = struct.pack(
        "<BBBBLHH20x",
        0x03,  # dBase III (no memo, no VFP 263-byte backlink extension)
        126,
        9,
        1,
        record_count,
        header_length,
        record_length,
    )
    descriptor = (
        field_name.encode("ascii").ljust(11, b"\x00")
        + b"C"
        + b"\x00\x00\x00\x00"
        + bytes([field_length, 0])
        + b"\x00" * 14
    )
    records = (b" " + payload) * record_count
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(header + descriptor + b"\x0d" + records + b"\x1a")


# ---------------------------------------------------------------------------
# individual smokes
# ---------------------------------------------------------------------------


def install_base(venv_dir: Path, wheel: Path) -> None:
    pip_install(venv_dir, str(wheel))


def install_extra(venv_dir: Path, wheel: Path, extra: str, dist_dir: Path) -> None:
    pip_install(venv_dir, "--find-links", str(dist_dir), f"dbfbridge[{extra}]")


def assert_base_contract(venv_dir: Path, wheel: Path, expected_version: str) -> None:
    code = (
        "import json, importlib.metadata, sys\n"
        "import dbfbridge\n"
        f"assert dbfbridge.__version__ == {expected_version!r}, dbfbridge.__version__\n"
        "import dbf_bridge\n"
        f"assert dbf_bridge.__version__ == {expected_version!r}\n"
        "installed = sorted({d.metadata['Name'].lower() for d in importlib.metadata.distributions()})\n"
        f"forbidden = {list(REQUIRED_BASE_ABSENT)!r}\n"
        "present = [name for name in forbidden if name in installed]\n"
        "assert not present, ('mandatory deps leaked into base install:', present)\n"
        "heavy = [m for m in ('dbf','dbfread','orjson','polars','openpyxl','xlsxwriter') if m in sys.modules]\n"
        "assert heavy == [] or heavy == ['dbfread'], heavy\n"
        "print(json.dumps({'version': dbfbridge.__version__, 'origin': dbfbridge.__file__, 'installed': installed}))\n"
    )
    out = snippet(venv_dir, code)
    payload = json.loads(out.strip().splitlines()[-1])
    if "site-packages" not in payload["origin"].replace("\\", "/"):
        raise SmokeFailure(f"dbfbridge did not come from the fresh venv: {payload['origin']}")
    print(f"  version={payload['version']} origin-in-venv=True base-inventory-clean=True")
    assert "dbfread" in payload["installed"], payload["installed"]


def direct_read_smoke(venv_dir: Path, fixture: Path, work: Path) -> None:
    direct_read_contract_smoke(venv_dir, fixture, work)


def direct_read_contract_smoke(
    venv_dir: Path,
    fixture: Path,
    work: Path,
    *,
    mazovia_fixture: Path | None = None,
    mazovia_sidecar: Path | None = None,
) -> None:
    """Direct Read contract smoke (progress/cancellation/explicit encoding).

    With ``mazovia_fixture``/``mazovia_sidecar`` the smoke additionally
    decodes REAL Mazovia bytes with the installed wheel and asserts the
    EXACT expected Polish text — proving correctness, not merely codec
    registration.
    """
    fixture_posix = str(fixture).replace("\\", "/")
    code = f"""
import json, sys
from pathlib import Path
from dbfbridge import (
    inspect_table, read_schema, iter_records, read_records, iter_raw_records,
    CancellationCheck, ReadCancelledError, ProgressEvent, ProgressCallback,
)

source = r"{fixture_posix}"

info = inspect_table(source)
assert info.record_count == 200, info.record_count
assert len(info.fields) == 4, len(info.fields)

schema = read_schema(source)
assert schema.record_count == 200

records = iter_records(source, memo="skip")
count = 0
try:
    for index, record in enumerate(records):
        count += 1
        if index == 9:
            break
finally:
    records.close()
assert count == 10, count

# --- progress + cancellation contract (base install, no extras) ---
progress_events = []
for record in iter_records(source, progress=progress_events.append):
    pass
assert progress_events, "progress events expected"
assert progress_events[-1].message == "completed"
assert progress_events[-1].current == 200 and progress_events[-1].total == 200
assert progress_events[-1].records == 200

cancelled = []
try:
    for record in iter_records(source, cancel_check=lambda: len(cancelled) >= 10):
        cancelled.append(record)
except ReadCancelledError as error:
    payload = error.to_dict()
    assert payload["code"] == "READ_CANCELLED", payload
    assert payload["context"]["scanned"] == 10 and payload["context"]["yielded"] == 10
else:
    raise SystemExit("cancel_check must stop the read")
assert len(cancelled) == 10

try:
    list(iter_records(source, cancel_check=lambda: True))
except ReadCancelledError as early:
    assert early.to_dict()["context"]["scanned"] == 0

page = read_records(source, offset=0, limit=100)
assert len(page.records) == 100 and page.next_offset == 100

raw_total = sum(1 for _ in iter_raw_records(source))
assert raw_total == 200, raw_total

# --- explicit Polish encoding overrides (fresh base venv proves the
# codecs are registered at operation time, not by import order) ---
from dbfbridge import EncodingUnknownError as _EncUnknown

# The historical module-level codec registrar must not run at import time:
# the codec must be UNREGISTERED after `import dbfbridge` and become
# available only through the operation (registration lifecycle proof).
try:
    b"x".decode("mazovia")
    raise SystemExit("mazovia codec must not be registered by import dbfbridge")
except LookupError:
    pass

explicit = list(iter_records(source, encoding="mazovia"))
assert len(explicit) == 200, len(explicit)
assert isinstance(explicit[0].values["NAME"], str)

# After the operation the codec IS available (process-wide, on demand).
b"\\x8c".decode("mazovia")

try:
    list(iter_records(source, encoding="definitely-not-a-real-codec"))
except _EncUnknown as unknown:
    unknown_payload = unknown.to_dict()
    assert unknown_payload["code"] == "ENCODING_UNKNOWN", unknown_payload
    json.dumps(unknown_payload)  # JSON-safe
else:
    raise SystemExit("unknown codec must raise EncodingUnknownError")

assert not list(Path(r"{work.as_posix()}").glob("**/*.partial"))
print("direct-read OK")
"""
    if mazovia_fixture is not None:
        # REAL Mazovia bytes decoded by the installed wheel to the EXACT
        # expected Polish text — correctness, not just registration.  The
        # expected text comes from the UTF-8 JSON sidecar written by the
        # outer harness (the -c code stays pure ASCII).
        code += f"""

# --- REAL Mazovia bytes decoded by the installed wheel ---
mazovia_source = r"{mazovia_fixture.as_posix()}"
mazovia_sidecar = r"{mazovia_sidecar.as_posix()}"
mazovia_expected = json.loads(Path(mazovia_sidecar).read_text(encoding="utf-8"))["expected"]

mazovia_records = list(iter_records(mazovia_source, encoding="mazovia"))
assert len(mazovia_records) == 1, len(mazovia_records)
mazovia_text = mazovia_records[0].values["TEKST"].rstrip()
assert mazovia_text == mazovia_expected, (mazovia_text, mazovia_expected)
print("mazovia-real-bytes OK")
"""
    snippet(venv_dir, code, cwd=work)


def migration_smoke(venv_dir: Path, fixture: Path, work: Path) -> None:
    code = f"""
import json
from pathlib import Path
from dbfbridge import export_dbf

out = Path("migration_out")
result = export_dbf(r"{str(fixture).replace(chr(92), "/")}", str(out), formats=("jsonl", "json", "csv"))
result.raise_for_errors()
for name in ("customers.jsonl", "customers.json", "customers.csv"):
    assert (out / name).is_file(), name
rows = [json.loads(line) for line in (out / "customers.jsonl").read_text(encoding="utf-8").splitlines() if line.strip()]
assert len(rows) == 200, len(rows)
print("migration OK")
"""
    snippet(venv_dir, code, cwd=work)


def negative_write_smoke(venv_dir: Path, export_dir: Path, work: Path) -> None:
    code = f"""
import json
from pathlib import Path
from dbfbridge import OptionalDependencyMissingError, reconstruct_dbf

out = Path("negative_write_out")
try:
    reconstruct_dbf(r"{str(export_dir).replace(chr(92), "/")}", str(out), input_format="jsonl")
except OptionalDependencyMissingError as error:
    payload = error.to_dict()
    assert payload["code"] == "OPTIONAL_DEPENDENCY_MISSING", payload
    assert payload["dependency"] == "dbf" and payload["extra"] == "write", payload
    assert payload["install_command"] == 'python -m pip install "dbfbridge[write]"', payload
else:
    raise SystemExit("reconstruct_dbf must fail without [write]")
assert not out.exists(), "zero output artifacts required"
print("negative-write OK")
"""
    snippet(venv_dir, code, cwd=work)


def negative_xlsx_smoke(venv_dir: Path, fixture: Path, work: Path) -> None:
    code = f"""
from pathlib import Path
from dbfbridge import OptionalDependencyMissingError, export_dbf

out = Path("negative_xlsx_out")
try:
    export_dbf(r"{str(fixture).replace(chr(92), "/")}", str(out), formats=("xlsx",))
except OptionalDependencyMissingError as error:
    payload = error.to_dict()
    assert payload["code"] == "OPTIONAL_DEPENDENCY_MISSING" and payload["extra"] == "xlsx", payload
else:
    raise SystemExit("xlsx export must fail without [xlsx]")
assert not out.exists(), "zero output artifacts expected"
print("negative-xlsx OK")
"""
    snippet(venv_dir, code, cwd=work)


def write_extra_smoke(venv_dir: Path, export_dir: Path, work: Path) -> None:
    code = f"""
from pathlib import Path
from dbfbridge import reconstruct_dbf, verify_conversion

out = Path("write_out")
result = reconstruct_dbf(r"{str(export_dir).replace(chr(92), "/")}", str(out), input_format="jsonl", overwrite=True)
result.raise_for_errors()
dbfs = list(out.rglob("*.dbf"))
assert dbfs, "reconstructed DBF missing"
print("write OK")
"""
    snippet(venv_dir, code, cwd=work)


def write_memo_extra_smoke(venv_dir: Path, memo_export_dir: Path, work: Path) -> None:
    code = f"""
from pathlib import Path
from dbfbridge import reconstruct_dbf

out = Path("write_memo_out")
result = reconstruct_dbf(r"{str(memo_export_dir).replace(chr(92), "/")}", str(out), input_format="jsonl", overwrite=True)
result.raise_for_errors()
assert list(out.rglob("*.dbf")), "DBF missing"
assert list(out.rglob("*.fpt")), "FPT missing for memo reconstruction"
print("write-memo OK")
"""
    snippet(venv_dir, code, cwd=work)


def xlsx_extra_smoke(venv_dir: Path, fixture: Path, work: Path) -> Path:
    code = f"""
from pathlib import Path
from dbfbridge import export_dbf

out = Path("xlsx_out")
result = export_dbf(r"{str(fixture).replace(chr(92), "/")}", str(out), formats=("xlsx",))
result.raise_for_errors()
assert list(out.rglob("*.xlsx")), "xlsx output missing"
print("xlsx OK")
"""
    snippet(venv_dir, code, cwd=work)
    return work / "xlsx_out"


def write_xlsx_extra_smoke(venv_dir: Path, xlsx_export_dir: Path, work: Path) -> None:
    code = f"""
from pathlib import Path
from dbfbridge import reconstruct_dbf

out = Path("write_xlsx_out")
result = reconstruct_dbf(r"{str(xlsx_export_dir).replace(chr(92), "/")}", str(out), input_format="xlsx", overwrite=True)
result.raise_for_errors()
assert list(out.rglob("*.dbf")), "reconstructed DBF missing"
print("write-xlsx OK")
"""
    snippet(venv_dir, code, cwd=work)


def fast_extra_smoke(venv_dir: Path, fixture: Path, work: Path) -> None:
    code = f"""
import importlib.util
assert importlib.util.find_spec("orjson") is not None, "orjson missing"
assert importlib.util.find_spec("polars") is not None, "polars missing"
from pathlib import Path
from dbfbridge import export_dbf

out = Path("fast_out")
result = export_dbf(r"{str(fixture).replace(chr(92), "/")}", str(out), formats=("jsonl", "json", "csv"))
result.raise_for_errors()
print("fast OK")
"""
    snippet(venv_dir, code, cwd=work)


def all_extra_smoke(venv_dir: Path, wheel: Path, repo_root: Path, work: Path) -> None:
    # The full release wheel smoke (fresh venv, Direct Read + legacy + CLI).
    _run(
        [
            sys.executable,
            str(repo_root / "scripts" / "release_wheel_smoke.py"),
            "--wheel",
            str(wheel),
            "--expected-version",
            _wheel_version(wheel),
        ]
    )
    # Reconstruction + XLSX paths inside the [all] venv.
    xlsx_dir = xlsx_extra_smoke(venv_dir, work / "fixtures" / "customers.dbf", work)
    write_xlsx_extra_smoke(venv_dir, xlsx_dir, work)
    print("all OK")


def _wheel_version(wheel: Path) -> str:
    name = wheel.name
    return name.split("-")[1]


# ---------------------------------------------------------------------------
# orchestration
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel", type=Path, default=None, help="existing feature wheel to test")
    parser.add_argument("--expected-version", default=None, help="assert the wheel version")
    parser.add_argument(
        "--keep-temp", action="store_true", help="keep the temporary work directory"
    )
    args = parser.parse_args(argv)

    wheel = args.wheel
    if wheel is None:
        dist = REPO_ROOT / "dist"
        wheels = sorted(dist.glob("dbfbridge-*.whl"))
        if not wheels:
            raise SmokeFailure("no wheel given and none found in dist/ (run `python -m build`)")
        wheel = wheels[-1]
    wheel = wheel.resolve()
    expected_version = args.expected_version or _wheel_version(wheel)

    work_root = Path(tempfile.mkdtemp(prefix="dbfbridge-pypi-smoke-"))
    dist_dir = wheel.parent
    try:
        print(f"wheel: {wheel}")
        print(f"expected version: {expected_version}")
        fixtures = prepare_fixtures(work_root)
        print(f"fixtures: {sorted(str(value) for value in fixtures.values())}")

        # 1) base install contract
        base = build_fresh_venv(work_root, "venv-base")
        install_base(base, wheel)
        assert_base_contract(base, wheel, expected_version)

        # 2) Direct Read on the base install (incl. REAL Mazovia bytes +
        # exact-text verification with the installed wheel)
        direct_read_contract_smoke(
            base,
            fixtures["flat"],
            work_root,
            mazovia_fixture=fixtures["mazovia_real"],
            mazovia_sidecar=fixtures["mazovia_sidecar"],
        )

        # 3) base migration (JSONL/JSON/CSV with fallbacks)
        migration_smoke(base, fixtures["flat"], work_root)

        # prepare export inputs with the base venv (export needs no [write])
        def _export(source_dbf: Path, formats: list[str], name: str) -> Path:
            out = work_root / name
            code = (
                "from pathlib import Path\n"
                "from dbfbridge import export_dbf\n"
                f'result = export_dbf(r"{source_dbf.as_posix()}", r"{out.as_posix()}", formats={formats!r}, overwrite=True)\n'
                "result.raise_for_errors()\n"
                "print('exported')\n"
            )
            snippet(base, code, cwd=work_root)
            return out

        export_jsonl = _export(fixtures["flat"], ["jsonl"], "export-jsonl")
        export_memo_jsonl = _export(fixtures["memo"], ["jsonl"], "export-memo-jsonl")

        # 4) negative smokes on the base install
        negative_write_smoke(base, export_jsonl, work_root)
        negative_xlsx_smoke(base, fixtures["flat"], work_root)

        # 5) [write]
        venv_write = build_fresh_venv(work_root, "venv-write")
        install_extra(venv_write, wheel, "write", dist_dir)
        write_extra_smoke(venv_write, export_jsonl, work_root)
        write_memo_extra_smoke(venv_write, export_memo_jsonl, work_root)

        # 6) [xlsx]
        venv_xlsx = build_fresh_venv(work_root, "venv-xlsx")
        install_extra(venv_xlsx, wheel, "xlsx", dist_dir)
        xlsx_dir = xlsx_extra_smoke(venv_xlsx, fixtures["flat"], work_root)

        # 7) [write,xlsx]
        venv_write_xlsx = build_fresh_venv(work_root, "venv-write-xlsx")
        install_extra(venv_write_xlsx, wheel, "write,xlsx", dist_dir)
        write_xlsx_extra_smoke(venv_write_xlsx, xlsx_dir, work_root)

        # 8) [fast]
        venv_fast = build_fresh_venv(work_root, "venv-fast")
        install_extra(venv_fast, wheel, "fast", dist_dir)
        fast_extra_smoke(venv_fast, fixtures["flat"], work_root)

        # 9) [all] — includes the full release wheel smoke
        venv_all = build_fresh_venv(work_root, "venv-all")
        install_extra(venv_all, wheel, "all", dist_dir)
        all_extra_smoke(venv_all, wheel, REPO_ROOT, work_root)

        print("PYPI INSTALL SMOKE: PASS")
        return 0
    finally:
        if args.keep_temp:
            print(f"work directory kept: {work_root}")
        else:
            shutil.rmtree(work_root, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
